# Assignment #4: NumPy + A few tuples/lists




### In this assignment, we will practice on NumPy, Tuple, Set, Dict using social network use case. 

**Please read the explanation in "H4.docx"**

# **Important**
- Do not delete or modify the first line in the given code cell.
- You work must be add in the provided area only. 
- You must not change the declaration of the provided functions.
- You are allowed to add your own functions.
- If you want to write your own program to test, add new code cell at the very end of the file and add your code there.


In [ ]:
import numpy as np

In [ ]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#1

def generate_adjacency_matrix(filename):
  # write your code here





  return A, person_names

In [ ]:
"""
from google.colab import files
uploaded = files.upload()
print('uploaded = ', uploaded)
"""
A, person_names = generate_adjacency_matrix("social_network.txt")
print(A)
print(person_names)

[[0 1 0 1 1]
 [1 0 0 1 0]
 [0 0 0 0 1]
 [1 1 0 0 1]
 [1 0 1 1 0]]
['A', 'B', 'C', 'D', 'E']


In [ ]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#2

def get_degree_matrix(A):
  # write your code here




  return D

In [ ]:
D = get_degree_matrix(A)
print(D)

[[3 0 0 0 0]
 [0 2 0 0 0]
 [0 0 1 0 0]
 [0 0 0 3 0]
 [0 0 0 0 3]]


In [ ]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#3

def get_names_with_highest_number_of_friends(D, person_names):
  # write your code here






  return all_max

In [ ]:
persons = get_names_with_highest_number_of_friends(D, person_names)
print(persons)

[('A', 0), ('D', 3), ('E', 4)]


In [ ]:
# HELPER FUNCTION
def get_liked_page_matrix(infile):
  liked_pages = []
  persons = []
  fr = open(infile, 'r')
  for line in fr:
    name, bits = line.strip().split(',')
    liked_page = [int(c) for c in bits]
    liked_pages.append(liked_page)
    persons.append(name)
  liked_pages_array = np.array(liked_pages)
  return liked_pages_array,persons

In [ ]:
"""
from google.colab import files
uploaded = files.upload()
print('uploaded = ', uploaded)
"""
liked_pages, persons = get_liked_page_matrix('liked_pages.txt')
print(liked_pages)
print(persons)


[[0 1 0 1 1 1 0]
 [1 0 0 1 0 1 1]
 [0 0 0 0 1 0 1]
 [1 1 0 0 1 0 0]
 [0 1 1 1 0 1 0]]
['A', 'B', 'C', 'D', 'E']


In [ ]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#4

def get_distance_matrix(Lp):
  # write your code here









  return distance_matrix

In [ ]:
Dt = get_distance_matrix(liked_pages)
print(Dt)

[[0.         0.33333333 0.2        0.4        0.6       ]
 [0.33333333 0.         0.2        0.16666667 0.33333333]
 [0.2        0.2        0.         0.25       0.        ]
 [0.4        0.16666667 0.25       0.         0.16666667]
 [0.6        0.33333333 0.         0.16666667 0.        ]]


In [ ]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Task#5

def get_all_most_similar_pairs(Dt, persons):
  # write your code here









  return pairs

In [ ]:
pairs = get_all_most_similar_pairs(Dt, persons)
print(pairs)

[('A', 'E')]
